# Generated by Django 4.1.4 on 2023-05-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auditprogramrepo_riskrepo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskrepo',
            old_name='department_id',
            new_name='department_name',
        ),
    ]
