# Generated by Django 4.1.4 on 2023-05-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_department_id_riskrepo_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskrepo',
            name='department_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
