# Generated by Django 4.2.3 on 2023-07-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_auditprogramrepo_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprogramrepo',
            name='department_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditprogramrepo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskrepo',
            name='department_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskrepo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
