# Generated by Django 4.2.3 on 2023-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_auditprogramrepo_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditprogramrepo',
            name='department_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
